#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate deterministic reciprocal/log lookup tables used by the TMU."""

from __future__ import annotations

import math
import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "generated" / "sst1_tmu_tables_pkg.sv"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Generated by tools/tmu/generate_tables.py; do not edit.",
        "`timescale 1ns/1ps",
        "package sst1_tmu_tables_pkg;",
        "",
        "    function automatic logic [7:0] sst1_log_fraction(input logic [7:0] index);",
        "        case (index)",
    ]
    for index in range(256):
        value = math.floor(math.log2(1.0 + index / 256.0) * 256.0)
        lines.append(f"            8'h{index:02x}: return 8'h{value:02x};")
    lines += [
        "        endcase",
        "    endfunction",
        "",
        "    function automatic logic [16:0] sst1_reciprocal_entry(input logic [8:0] index);",
        "        case (index)",
    ]
    for index in range(257):
        value = round((1 << 24) / (256 + index))
        lines.append(f"            9'h{index:03x}: return 17'h{value:05x};")
    lines += [
        "            default: return 17'd0;",
        "        endcase",
        "    endfunction",
        "",
        "endpackage",
        "",
    ]
    generated = "\n".join(lines)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"generated file is stale: {OUTPUT}")
    else:
        OUTPUT.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
