#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate zSST programming-contract artifacts from registers.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys


PROJECT = Path(__file__).resolve().parents[2]
DATABASE = Path(__file__).with_name("registers.json")
OUTPUTS = {
    PROJECT / "generated" / "sst1_regs_pkg.sv": "sv",
    PROJECT / "software" / "include" / "zsst1_regs.h": "c",
    PROJECT / "REGISTER_MAP.md": "markdown",
    PROJECT / "sim" / "models" / "registers.json": "json",
}


def symbol(name: str) -> str:
    value = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").upper()
    if not value or value[0].isdigit():
        value = "R_" + value
    return value


def expand(database: dict) -> tuple[list[dict], list[dict]]:
    registers = []
    for group in database["groups"]:
        defaults = group.get("defaults", {})
        for item in group["registers"]:
            registers.append({**defaults, **item, "group": group["name"]})
    for series in database.get("series", []):
        for index in range(series["count"]):
            registers.append(
                {
                    **series["defaults"],
                    "name": series["name"].format(index=index),
                    "address": series["base"] + index * series["stride"],
                    "description": series["description"].format(index=index),
                    "group": series["group"],
                }
            )
    registers.sort(key=lambda item: item["address"])
    aliases = sorted(database.get("aliases", []), key=lambda item: item["address"])
    return registers, aliases


def validate(registers: list[dict], aliases: list[dict]) -> None:
    names = set()
    addresses = set()
    by_name = {}
    for item in registers:
        if item["name"] in names:
            raise ValueError(f"duplicate register name {item['name']}")
        if item["address"] in addresses or item["address"] & 3 or item["address"] > 0x3FC:
            raise ValueError(f"invalid/duplicate register address 0x{item['address']:03x}")
        if item["access"] not in {"ro", "wo", "rw"}:
            raise ValueError(f"invalid access for {item['name']}")
        names.add(item["name"])
        addresses.add(item["address"])
        by_name[item["name"]] = item
        used = 0
        for field in item.get("fields", []):
            if not 0 <= field["lsb"] <= field["msb"] <= 31:
                raise ValueError(f"invalid field {item['name']}.{field['name']}")
            mask = ((1 << (field["msb"] - field["lsb"] + 1)) - 1) << field["lsb"]
            if used & mask:
                raise ValueError(f"overlapping field {item['name']}.{field['name']}")
            used |= mask
    alias_addresses = set()
    for alias in aliases:
        if alias["target"] not in by_name:
            raise ValueError(f"alias {alias['name']} has unknown target")
        if alias["address"] & 3 or not 0x200000 <= alias["address"] < 0x200400:
            raise ValueError(f"alias {alias['name']} has invalid address")
        if alias["address"] in alias_addresses:
            raise ValueError(f"duplicate alias address 0x{alias['address']:06x}")
        alias_addresses.add(alias["address"])


def render_sv(registers: list[dict], aliases: list[dict]) -> str:
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Generated by tools/registers/generate.py; do not edit.",
        "`timescale 1ns/1ps",
        "package sst1_regs_pkg;",
        "    typedef enum logic [1:0] {",
        "        ZSST1_REG_NONE = 2'd0, ZSST1_REG_RO = 2'd1,",
        "        ZSST1_REG_WO = 2'd2, ZSST1_REG_RW = 2'd3",
        "    } zsst1_reg_access_t;",
        "",
    ]
    for item in registers:
        lines.append(
            f"    localparam logic [11:0] ZSST1_REG_{symbol(item['name'])} = 12'h{item['address']:03x};"
        )
    lines += ["", "    function automatic zsst1_reg_access_t zsst1_reg_access(input logic [11:0] address);", "        case (address)"]
    access = {"ro": "ZSST1_REG_RO", "wo": "ZSST1_REG_WO", "rw": "ZSST1_REG_RW"}
    for item in registers:
        lines.append(f"            12'h{item['address']:03x}: return {access[item['access']]};")
    lines += ["            default: return ZSST1_REG_NONE;", "        endcase", "    endfunction", ""]
    commands = [item for item in registers if item.get("side_effect") == "command"]
    lines += ["    function automatic logic zsst1_is_command(input logic [11:0] address);", "        case (address)"]
    for item in commands:
        lines.append(f"            12'h{item['address']:03x}: return 1'b1;")
    lines += ["            default: return 1'b0;", "        endcase", "    endfunction", ""]
    for function_name, property_name in (
        ("zsst1_reg_fifo", "fifo"),
        ("zsst1_reg_sync", "sync"),
    ):
        lines += [f"    function automatic logic {function_name}(input logic [11:0] address);", "        case (address)"]
        for item in registers:
            if item.get(property_name):
                lines.append(f"            12'h{item['address']:03x}: return 1'b1;")
        lines += ["            default: return 1'b0;", "        endcase", "    endfunction", ""]

    lines += ["    function automatic logic [3:0] zsst1_reg_chip_mask(input logic [11:0] address);", "        case (address)"]
    for item in registers:
        chips = item["chips"]
        mask = (1 if "FBI" in chips else 0) | (2 if "TREX" in chips else 0)
        lines.append(f"            12'h{item['address']:03x}: return 4'h{mask:x};")
    lines += ["            default: return 4'h0;", "        endcase", "    endfunction", ""]

    float_aliases = []
    by_name = {item["name"]: item for item in registers}
    fixed_formats = []
    for item in registers:
        match = re.search(r"signed\s+(\d+)\.(\d+)", item["description"])
        if match is not None:
            fixed_formats.append((item, int(match.group(1)) + int(match.group(2))))
    for item in registers:
        if item.get("side_effect") != "float_state":
            continue
        target_name = item["name"][1:]
        target = by_name.get(target_name)
        if target is None:
            raise ValueError(f"float register {item['name']} has no {target_name} target")
        match = re.search(r"signed\s+\d+\.(\d+)", target["description"])
        if match is None:
            raise ValueError(f"fixed register {target_name} has no signed format")
        fraction = int(match.group(1))
        width_match = re.search(r"signed\s+(\d+)\.(\d+)", target["description"])
        assert width_match is not None
        width = int(width_match.group(1)) + int(width_match.group(2))
        float_aliases.append((item, target, fraction, width))

    lines += ["    function automatic logic zsst1_is_float_alias(input logic [11:0] address);", "        case (address)"]
    for item, _, _, _ in float_aliases:
        lines.append(f"            12'h{item['address']:03x}: return 1'b1;")
    lines += ["            default: return 1'b0;", "        endcase", "    endfunction", ""]
    for function_name, width_bits, value_index in (
        ("zsst1_float_target", 12, 1),
        ("zsst1_float_fraction", 6, 2),
        ("zsst1_float_width", 6, 3),
    ):
        lines += [f"    function automatic logic [{width_bits - 1}:0] {function_name}(input logic [11:0] address);", "        case (address)"]
        for values in float_aliases:
            item = values[0]
            value = values[value_index]
            if isinstance(value, dict):
                literal = f"12'h{value['address']:03x}"
            else:
                literal = f"{width_bits}'d{value}"
            lines.append(f"            12'h{item['address']:03x}: return {literal};")
        lines += [f"            default: return {width_bits}'d0;", "        endcase", "    endfunction", ""]
    lines += ["    function automatic logic [5:0] zsst1_fixed_width(input logic [11:0] address);", "        case (address)"]
    for item, width in fixed_formats:
        lines.append(f"            12'h{item['address']:03x}: return 6'd{width};")
    lines += ["            default: return 6'd32;", "        endcase", "    endfunction", ""]
    lines += [
        "    function automatic logic [31:0] zsst1_canonical_fixed(",
        "        input logic [11:0] address, input logic [31:0] value);",
        "        logic [5:0] width;",
        "        begin",
        "            width = zsst1_fixed_width(address);",
        "            case (width)",
        "                6'd16: return {{16{value[15]}}, value[15:0]};",
        "                6'd24: return {{8{value[23]}}, value[23:0]};",
        "                default: return value;",
        "            endcase",
        "        end",
        "    endfunction",
        "",
    ]
    lines += ["    function automatic logic [11:0] zsst1_remap_register(input logic [11:0] address);", "        case (address)"]
    for alias in aliases:
        lines.append(
            f"            12'h{alias['address'] & 0xfff:03x}: return 12'h{by_name[alias['target']]['address']:03x};"
        )
    lines += ["            default: return address;", "        endcase", "    endfunction", "", "endpackage", ""]
    return "\n".join(lines)


def render_c(registers: list[dict]) -> str:
    lines = [
        "/* SPDX-License-Identifier: Apache-2.0 */",
        "/* Generated by tools/registers/generate.py; do not edit. */",
        "#ifndef ZSST1_REGS_H",
        "#define ZSST1_REGS_H",
        "",
        "#define ZSST1_PCI_VENDOR_ID 0x121a",
        "#define ZSST1_PCI_DEVICE_ID 0x0001",
        "#define ZSST1_BAR_SIZE       0x01000000u",
        "",
    ]
    for item in registers:
        lines.append(f"#define ZSST1_REG_{symbol(item['name']):<24} 0x{item['address']:03x}u")
        for field in item.get("fields", []):
            width = field["msb"] - field["lsb"] + 1
            mask = ((1 << width) - 1) << field["lsb"]
            prefix = f"ZSST1_{symbol(item['name'])}_{symbol(field['name'])}"
            lines.append(f"#define {prefix + '_SHIFT':<40} {field['lsb']}u")
            lines.append(f"#define {prefix + '_MASK':<40} 0x{mask:08x}u")
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def render_markdown(database: dict, registers: list[dict], aliases: list[dict]) -> str:
    lines = [
        "# SST-1 register contract",
        "",
        "Generated from `tools/registers/registers.json` by `make generate`.",
        "Unknown silicon reset values are shown as `unknown`; they are not assumed zero.",
        "",
        "| Address | Name | Access | Chips | FIFO / sync | Reset | Description |",
        "|---:|---|:---:|---|:---:|---|---|",
    ]
    for item in registers:
        reset = "unknown" if item.get("reset") is None else f"`0x{item['reset']:08x}`"
        fifo_sync = f"{'yes' if item.get('fifo') else 'no'} / {'yes' if item.get('sync') else 'no'}"
        lines.append(
            f"| `0x{item['address']:03x}` | `{item['name']}` | {item['access'].upper()} | "
            f"{item['chips']} | {fifo_sync} | {reset} | {item['description']} |"
        )
    lines += ["", "## Alternate triangle map", "", "When `fbiInit3[0]` and PCI address bit 21 are set, these low offsets map to the canonical registers below.", "", "| BAR address | Alias | Canonical register |", "|---:|---|---|"]
    for alias in aliases:
        lines.append(f"| `0x{alias['address']:06x}` | `{alias['name']}` | `{alias['target']}` |")
    lines += ["", "## Sources", ""]
    for source in database["sources"]:
        lines.append(f"- {source}")
    lines.append("")
    return "\n".join(lines)


def generated_model(database: dict, registers: list[dict], aliases: list[dict]) -> str:
    value = {
        "schema_version": database["schema_version"],
        "registers": registers,
        "aliases": aliases,
        "sources": database["sources"],
    }
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    database = json.loads(DATABASE.read_text(encoding="utf-8"))
    registers, aliases = expand(database)
    validate(registers, aliases)
    renders = {
        "sv": render_sv(registers, aliases),
        "c": render_c(registers),
        "markdown": render_markdown(database, registers, aliases),
        "json": generated_model(database, registers, aliases),
    }
    failures = []
    for path, kind in OUTPUTS.items():
        content = renders[kind]
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                failures.append(str(path.relative_to(PROJECT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if failures:
        print("generated register artifact mismatch:", *failures, sep="\n  ", file=sys.stderr)
        print("run: python3 tools/registers/generate.py", file=sys.stderr)
        return 1
    print(f"{'verified' if args.check else 'generated'} {len(registers)} registers and {len(aliases)} aliases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
